### ISSUE TITLE
Publish to gh-pages branch

### ISSUE THREAD

**Issue by vyrnix9582046173** [exokitxr/exokit-docs-site#12]
Currently the site built from here has been being pushed to https://github.com/exokitxr/exokitxr.github.io , which uses gh pages / cname. 

We can simplify that by publishing the generated static site to the `gh-pages` branch in this repo instead of adding another repository that hosts the static site.

**Comment by vyrnix9582046173** [comment]
Done 4bbd20f https://exokitxr.github.io/exokit-site/ 

The process is simpler now:
1. `npm run generate`
2. push `public/*` to `gh-pages` branch of this repo

------------------------------------------

Need to now make the transfer over to this repo:
- point domain to here
- delete https://github.com/exokitxr/exokitxr.github.io repo, use `exokit.org` domain in CNAME for this repo

**Comment by avaer** [comment]
Can this one be closed?

**Comment by vyrnix9582046173** [comment]
Yes, `exokit.org` is now pointing to this repo's `gh-pages` branch.
