### ISSUE TITLE
Landing page messaging

### ISSUE THREAD

**Issue by vyrnix9582046173** [exokitxr/exokit-docs-site#3]
This issue is to bring up the landing page messaging and plan out how to improve the messaging.

## Top of landing page
- A New XR Engine Approaches
Run and ship WebXR apps on
Standalone, Magic Leap, Desktop and Mobile.

## Gradient scrolldown sequence 

- What is Exokit?
Exokit is an XR engine that runs your code as native.

- Power up your WebXR app
Exokit runs regular HTML+JS WebXR sites. Add hardware bindings, native code, and more with the APIs Exokit gives you access to. 

- Run apps in Exokit
Run your app in Exokit with a URL. Or, run 5 instances in multiplayer AR. Debug it all with standard DevTools.

- Cross-platform support with Exokit
Write your app once, export to run on any of Exokit's supported devices.

## Minecraft avatars running sequence 

- Runs Existing Code
Exokit is an XR engine, not a web browser. It's layers of web-powererd realities, not screens floating in space.  
> This is repeated x3:

- Native Javascript
Exokit is an XR engine, not a web browser. It's layers of web-powererd realities, not screens floating in space.

-  Futuristic APIs
Exokit is an XR engine, not a web browser. It's layers of web-powererd realities, not screens floating in space.

- Package for Stores
Exokit is an XR engine, not a web browser. It's layers of web-powererd realities, not screens floating in space.

## **Runs on Exokit**

The expanse, active theory, emukit

## Call to action:
- Latest WebXR
features, today.
Get Started

**Comment by vyrnix9582046173** [comment]
My initial thoughts are that "Made with Exokit" is not completely accurate.

**Comment by avaer** [comment]
> My initial thoughts are that "Made with Exokit" is not completely accurate.

Probably not. Maybe "Runs on Exokit" or "Our friends" or "Our allies in XR"?

**Comment by vyrnix9582046173** [comment]
### This is what I see as needing to be changed here:

> What is Exokit?
Exokit is an XR engine that runs your code as native.
  
The Exokit Engine is a native 3D XR web engine. 
  
---------------------------------------
  

> Runs Existing Code
Exokit is an XR engine, not a web browser. It's layers of web-powererd realities, not screens floating in space.  
  
Use the code you've written in your favorite 3D framework. The Exokit Engine supports any 3D web framework.

> Native Javascript
Exokit is an XR engine, not a web browser. It's layers of web-powererd realities, not screens floating in space.

Web APIs
Exokit provides native hooks for WebGL, WebXR, WebVR, WebAudio, and other APIs used for immersive experiences.   


> Futuristic APIs
Exokit is an XR engine, not a web browser. It's layers of web-powererd realities, not screens floating in space.
 
Extensible
The open source nature of the Exokit Engine allows for permission-less innovation. Fork the Exokit Engine, add your own custom bindings, and then pull request upstream to share your addition.

> Package for Stores
Exokit is an XR engine, not a web browser. It's layers of web-powererd realities, not screens floating in space.
  
Write your code once, export your XR site as a native executable or package for your device(s) of choice.

----------------------------------------- 

> Made with Exokit
  
Runs on Exokit
