### ISSUE TITLE
Make docs more readable

### ISSUE THREAD

**Issue by vyrnix9582046173** [exokitxr/exokit-docs-site#4]
- more traditional font, and more delineation (lines)
- right sidebar removed

![](https://cdn.discordapp.com/attachments/563734959081127965/574109799080263681/Capture_24.PNG)

**Comment by avaer** [comment]
The right sidebar might be ok if we color/add separators for the rest of the design, as well as use a more traditional paragraph font.

**Comment by vyrnix9582046173** [comment]
![moocCapture](https://user-images.githubusercontent.com/29695350/57206762-00bdf900-6f8e-11e9-8334-0ad986dd00aa.PNG)


![docxCapture](https://user-images.githubusercontent.com/29695350/57206746-db30ef80-6f8d-11e9-8e3a-3425c38b7cfd.PNG)

updated docs font to Roboto (used by node.js docs)

**Comment by avaer** [comment]
Thanks, I think that makes things more legible.

**Comment by vyrnix9582046173** [comment]
![oo](https://media.discordapp.net/attachments/563734959081127965/574816876555665418/002moocCapture.png)

Going to add an exobot like this mock above
