### ISSUE TITLE
Document 11.6.0 requirement

### ISSUE THREAD

**Issue by avaer** [exokitxr/exokit-docs-site#5]
I couldn't find any documentation on the site regarding the build requirement to use `node` `11.6.0`.

it would probably belong [here](https://exokit.org/docs/sdk/buildFromSource.html).

**Comment by vyrnix9582046173** [comment]
I agree, I'll add that today.

**Comment by vyrnix9582046173** [comment]
Closed by https://github.com/exokitxr/exokit/pull/1015 .
