### ISSUE TITLE
Search crashes docs site

### ISSUE THREAD

**Issue by avaer** [exokitxr/exokit-docs-site#6]
The left sidebar Algolia search functianlity crashes the site:

```
docsearch.min.js:2 Uncaught Error: Error: No input element in the page matches .docs-search-sidebar .search-field
    at Function.checkArguments (docsearch.min.js:2)
    at new DocSearch (docsearch.min.js:2)
    at Factory (docsearch.min.js:2)
    at vr-headsets-and-webvr-browsers.html:162
vr-headsets-and-webvr-browsers.html#what-are-the-differences-between-headsets:1 Failed to load resource: the server responded with a status of 404 ()
```

To repro, search for `11.6.0` and click the first link:

![Capture 25](https://user-images.githubusercontent.com/6926057/57181959-f6094400-6e67-11e9-9713-0f1920c34419.PNG)

**Comment by vyrnix9582046173** [comment]
I think that is just that they are pages that are cached that don't actually exist and will be fixed when there is a crawl and it is updated. Which should be fixed within 24 hours;

> Now that DocSearch is set, you don't have anything else to do. We'll keep crawling your website every day and update your search results automatically. All we ask is that you keep the "search by Algolia" logo next to your search results

https://community.algolia.com/docsearch/how-does-it-work.html#you-update-your-website

**Comment by vyrnix9582046173** [comment]
The 404 page is working for these missing pages, but it looks like the 24 hour crawl hasn't happened.. Contacted Algolia:

> Please expect some delay (not more than a week)

**Comment by vyrnix9582046173** [comment]
Contacted on Algolia's discord:
 >  i'll move the ownership of the project to your email and we'll reactivate it

**Comment by vyrnix9582046173** [comment]
>  Updated :white_check_mark:

Updated by Algolia. Closing now.

**Comment by avaer** [comment]
Is there a possibility of us having a non-rendering site due to page moves in the future? Or will there be a 404 page at least?

**Comment by vyrnix9582046173** [comment]
There will always be a 404 page. There was one in this case, but it was white text on a white background, so it was not visible.

**Comment by avaer** [comment]
Cool, but it will be visible going forward now, correct?

i.e. will this show in the Algolia crash case?

![Capture 26](https://user-images.githubusercontent.com/6926057/57412252-09951180-71be-11e9-88fa-f51747f3702e.PNG)

**Comment by vyrnix9582046173** [comment]
Yes, can test 404 page with: https://exokit.org/docs/notarealpage.html
